### ISSUE TITLE
PiMotor module cant be imported

### ISSUE THREAD

**Issue by kjblems** [sbcshop/MotorShield#11]
I have tried looking for a page for me to download the PiMotor module for the program but the page given in the manual is unavailable, i have searched the web for other solutions but cannot find anything even to do with PiMotor. Is there a link to a download available?

Kieron

**Comment by sbcshop** [comment]
Hi Kieron,

Open the terminal and write the following command to download the Motor Shield code and manual:

git clone https://github.com/sbcshop/MotorShield.git
